name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ## for contributor testing
  flutter_locales:
    path: ../
  ## for developer [uncomment the following line and remove above line]
  # flutter_locales: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/locales/