name: "app_local"
description: "A Flutter package for easy app localization using JSON files, supporting device default language detection and dynamic language switching without app restart"
version: "1.1.3"
repository: "https://github.com/abom-me/app_local"
documentation: "https://github.com/abom-me/app_local"
issue_tracker: "https://github.com/abom-me/app_local/issues"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.abom.applocal.app_lang
        pluginClass: AppLangPlugin
      ios:
        pluginClass: AppLangPlugin
      macos:
        pluginClass: AppLangPlugin


